feat: создать базовую структуру приложения
Warckut/landing-2024 pull request #1
Opened 2024-06-17 17:16 UTC by Warckut

Cоздана базовая структура приложения

2024-06-25 10:20 UTC, tvivls requested changes

2024-06-25 10:20 UTC, tvivls commented on src/App.jsx
> +      <Route path='/signUp' element={<SignUp />} />
можно записать короче, сделав массив объектов
потом использовать этот массив здесь

2024-06-25 12:11 UTC, trallik74 commented on src/App.jsx
> +      <Route path='/signUp' element={<SignUp />} />
Как то так?

```
const routes = [
  { path: '/', element: Home },
  { path: '/signIn', element: SignIn },
  { path: '/signUp', element: SignUp },
];

function App() {
  return (
    <Routes>
      {routes.map((route, index) => (
        <Route key={`${route.path}_${index}`} path={`${route.path}`} element={<route.element />} />
      ))}
    </Routes>
  );
}
```

2024-06-25 12:19 UTC, tvivls commented on src/App.jsx
> +      <Route path='/signUp' element={<SignUp />} />
да
можно еще сразу сделать деструктуризацию route, но это скорее вкусовщина) как тебе удобно

2024-07-08 08:34 UTC, Warckut commented
@tvivls, готово

2024-07-09 13:08 UTC, tvivls requested changes

2024-07-09 13:08 UTC, tvivls commented on src/App.jsx
> +];
константы выносите в отдельные файлы
например в const.js или const/routes.js

2024-07-09 13:08 UTC, tvivls commented on src/assets/styles/variables.css
> +:root {
имена для переменных тоже исправь
не должно быть привязки к конкретному цвету (white, gray-10, gray-20, ...)
--color-error, --color-success - норм названия

2024-07-09 13:08 UTC, tvivls commented on src/index.css
на мой взгляд, тут много дублирования. Можно сгруппировать

2024-07-12 14:02 UTC, Warckut commented
@tvivls, последние замечания исправлены

2024-07-12 15:21 UTC, tvivls approved these changes
давайте сливать

2024-07-12 15:37 UTC, merged