Feature/blocks with graphics
Warckut/landing-2024 pull request #2
Opened 2024-06-23 12:28 UTC by trallik74

2024-06-25 11:55 UTC, tvivls requested changes

2024-06-25 11:55 UTC, tvivls commented on src/components/Knowledge/Knowledge.jsx
> +                    <path d='M12.1914 22C6.66841 22 2.19141 17.523 2.19141 12C2.19141 6.477 6.66841 2 12.1914 2C17.7144 2 22.1914 6.477 22.1914 12C22.1914 17.523 17.7144 22 12.1914 22ZM12.1914 20C14.
выглядит страшно
выноси в отдельную картинку
так со всеми svg'шками

2024-06-25 11:55 UTC, tvivls commented on src/components/Faq/Faq.module.css
> +  gap: 64px;
у вас же есть переменные, используй 
ниже аналогично

2024-06-25 11:55 UTC, tvivls commented on src/components/Faq/Faq.module.css
> +  padding-bottom: 103px;
откуда такие цифры?)
ниже тоже

2024-06-25 11:55 UTC, tvivls commented on src/components/Faq/Faq.module.css
> +.wrapper::before {
можно сократить before и after
все равно дублируются стили

2024-06-25 11:55 UTC, tvivls commented on src/components/Faq/Faq.module.css
> +@media (max-width: 1228px) {
откуда такие цифры?
выглядит странно 🤔 
используй стандартные брейкпоинты 1280, 1024, 768,... если это возможно

2024-06-25 11:55 UTC, tvivls commented on src/components/Knowledge/Knowledge.jsx
> +            <a href='#' className={`${styles.link} ${styles.linkVariantContained}`}>
в таких случаях можно использовать библиотеку `classnames`

2024-06-25 11:55 UTC, tvivls commented on src/components/Knowledge/Knowledge.module.css
> +  gap: 16px;
используй `--spacing-`

2024-06-25 11:55 UTC, tvivls commented on src/components/Knowledge/Knowledge.module.css
> +  max-width: 664px;
не используй точные цифры для контейнеров, тем более такие непонятные
используй %, задавай через margin, padding

2024-06-25 11:55 UTC, tvivls commented on src/components/Slider/Slider.module.css
> +  background-image: url(../../assets/svg/chevron-right.svg);
не злоупотребляй таким
использовать для картинок в качестве фона - ок, это просто картинки.
но в подобных местах я бы использовала html теги, все-таки это иконка

2024-06-25 11:55 UTC, tvivls commented on src/components/Slider/Slider.module.css
> +}
уже писала выше
используй % + стандартные брейкпоинты
исправь везде, пожалуйста

2024-06-25 11:55 UTC, tvivls commented on src/components/Slider/index.js
> +export default Slider;
тут же уже есть export [src/components/Slider/Slider.jsx](https://github.com/Warckut/landing-2024/pull/2/files#diff-594fbcc3322eeaa75ec0060b7671b7503268d2e6344fee5e6f9fd51020156dbc)
зачем этот ?

2024-06-25 11:55 UTC, tvivls commented on src/utils/chartApi.js
> +  { x: 'Янв', y: 250 },
можно сократить, вынести что-нибудь?

2024-06-25 11:55 UTC, tvivls commented on src/utils/chartApi.js
> +  datasets: [
можно убрать дублирование свойств с помощью spread оператора

2024-06-25 12:15 UTC, tvivls commented
почему использовал modules, а не css-in-js?)
просто интересно

2024-06-25 12:40 UTC, trallik74 commented on src/components/Faq/Faq.module.css
> +  padding-bottom: 103px;
Размеры из фигмы, это фоновые изображения. Задал через паддинги т.к. в каком то из комментариев ты говорила что через ширину этого делать почему-то не стоит.

2024-06-25 12:43 UTC, trallik74 commented on src/components/Slider/Slider.module.css
> +  background-image: url(../../assets/svg/chevron-right.svg);
Не очень понимаю, это же кнопка почему ей так не стоит задавать ее иконку? На доступность это не должно сказаться т.к я им задал aria-label, в чем тогда другие причины этого не делать?

2024-06-25 12:47 UTC, trallik74 commented on src/components/Faq/Faq.module.css
> +@media (max-width: 1228px) {
т.к. у нас в макете нет адаптива под эти экраны, я делал брекпоинты там, где моя верстка ломалась и делал это так чтобы отступы не выглядели слишком большими.

2024-06-25 12:52 UTC, tvivls commented on src/components/Faq/Faq.module.css
> +  padding-bottom: 103px;
я думаю, можно округлить. не обязательно делать pixel perfect

а задавать ширину/высоту контенту **через px** не желательно, потому что, могут возникать проблемы с масштабируемостью, при адаптиве. 
Гораздо проще задать их через % например.
Другой пример: для кнопок проще задавать не фиксированную ширину/высоту, а padding'и

2024-06-25 12:53 UTC, trallik74 commented on src/components/Slider/index.js
> +export default Slider;
Мне казалось, что это очень распространённая на проектах техника, чтобы потом писать импорт компоненты до папки а не файла.

2024-06-25 12:56 UTC, trallik74 commented on src/utils/chartApi.js
> +  { x: 'Янв', y: 250 },
Наверное можно все 'x' вынести отдельно в лейблы и оставить только 'y', но не уверен что все будет работать так же. Попробую

2024-06-25 12:57 UTC, trallik74 commented on src/components/Knowledge/Knowledge.jsx
> +            <a href='#' className={`${styles.link} ${styles.linkVariantContained}`}>
Согласен, но на созвоне мы решили выбрать такой.

2024-06-25 13:00 UTC, trallik74 commented
> почему использовал modules, а не css-in-js?) просто интересно

Так решил общим мнением, т.к. с модулями работали почти все, а styledComponents/etc. не использовал никто.

2024-06-25 13:02 UTC, trallik74 commented on src/components/Faq/Faq.module.css
> +  padding-bottom: 103px;
Ты имеешь в виду retina мониторы?

2024-06-25 13:08 UTC, tvivls commented
> > почему использовал modules, а не css-in-js?) просто интересно
> 
> Так решил общим мнением, т.к. с модулями работали почти все, а styledComponents/etc. не использовал никто.

не бойтесь нового стека, познакомитесь в процессе выполнения задания. Просто в следующих заданиях по-любому будете использовать styled-components или emotion, а также разные ui kit'ы, тк они на многих проектах используются

2025-02-25 11:32 UTC, osakac reviewed
everything is fine

2025-02-25 11:33 UTC, closed without merging