Feature/header layout
Warckut/landing-2024 pull request #4
Opened 2024-06-26 08:12 UTC by Warckut

Добавлен Header и первые 3 блока лэндинга

2024-06-26 09:54 UTC, tvivls commented
направление ветки в base_structure, а не в main

2024-07-01 12:32 UTC, osakac requested changes

2024-07-01 12:32 UTC, osakac commented on src/index.css
> +}
ширина контейнера должна быть 1280px + горизонтальные отступы по 16px, а у тебя получается 1312px ширина + отступы по 16px

2024-07-01 18:09 UTC, tvivls requested changes
насчет глобальных стилей к тегам
если вы их не предопределяете - пусть будут
но если приходится их где-то менять - делайте классы

с заголовками, ссылками еще ок, но div'ам например точно не надо писать стили

и у вас по-разному называются стили, у Максима они в camelCase, тут я бы тоже так сделала

2024-07-01 18:09 UTC, tvivls commented on src/assets/svg/logo-mobile.svg
в чем отличие от src/assets/svg/logo.svg?

2024-07-01 18:09 UTC, tvivls commented on src/assets/svg/menu-blue.svg
аналогично
в чем разница с src/assets/svg/menu.svg

2024-07-01 18:09 UTC, tvivls commented on src/components/AboutProject/AboutProject.jsx
> +      <div className={'container'}>
```suggestion
      <div className="container">
```
обычно пишут так.
а с styles уже будет 
`<div className={styles.yourClass}>`

исправь везде

2024-07-01 18:09 UTC, tvivls commented on src/components/AboutProject/AboutProject.module.css
> +.about__main h2 {
не пиши стили к тегам, используй классы
исправь везде

2024-07-01 18:09 UTC, tvivls commented on src/components/AboutProject/AboutProject.module.css
> +.about__advgs {
название ни о чем не говорит

2024-07-01 18:09 UTC, tvivls commented on src/components/AboutProject/AboutProject.module.css
> +.about__advg {
название тоже плохое
+ легко перепутать с about__advgs

2024-07-01 18:09 UTC, tvivls commented on src/components/Articles/Articles.jsx
> +              <p>Врач-невролог из Москвы, Иванов Иван Иванович, отвечает на частые вопросы касающиеся проблемы ...</p>
давай внутри карточки обрезать сам текст, а не руками прописывать троеточие

2024-07-01 18:09 UTC, tvivls commented on src/components/Articles/Articles.module.css
> +.articles>div>button {
теги 💀

2024-07-01 18:09 UTC, tvivls commented on src/components/Header/Bottom/Bottom.jsx
> +  const { scroll } = props;
можно сделать деструктуризацию сразу на 5 строке
везде исправь

2024-07-01 18:09 UTC, tvivls commented on src/components/Header/Header.module.css
> +  background-color: white;
пиши в едином стиле
#ffffff, либо white, либо #FFFFFF

2024-07-01 18:09 UTC, tvivls commented on src/index.css
> +button.btn-primary {
по-моему очень сложно описано

2024-07-01 18:09 UTC, tvivls commented on src/pages/Home/Home.jsx
> +  const categories = [
вынеси в константы

2024-07-01 18:09 UTC, tvivls commented on src/pages/Home/Home.jsx
> +    let lastScroll = scrollPos();
без let не обойтись?

2024-07-01 18:10 UTC, tvivls commented
и исправь название картинок на более понятные

2024-07-01 18:22 UTC, tvivls commented
<img width="1206" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/60910148-7c99-43f9-a519-e7c40c1bb2e7">
'Узнать больше' на разной высоте.

<img width="524" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/cfc2a141-15f5-4bdc-8543-eefd760897d2">
исправь ширину селекта.

2024-07-08 08:20 UTC, Warckut commented
@tvivls, исправил замечания

2024-07-16 18:04 UTC, tvivls requested changes

2024-07-16 18:04 UTC, tvivls commented on src/components/Articles/Articles.jsx
> +                Читая статьи, и получая консультации на нашем сайте, вы часто будете встречаться dsfsdfdsfsdfsdfsd
ну можно было lorem ipsum дописать)

2024-07-16 18:04 UTC, tvivls commented on src/components/Header/Mobile/Mobile.jsx
> +  const [refSB, showSB, setShowSB] = usePopup();
```suggestion
  const [refSidebar, showSidebar, setShowSidebar] = usePopup();
```

2024-07-16 18:04 UTC, tvivls commented on src/components/Main/Main.module.css
> +.main__item {
в остальных файлах используешь camelCase, исправь и тут пж

2024-07-16 18:04 UTC, tvivls commented on src/components/Navigation/Navigation.jsx
> +        </li>
можно сократить

2024-07-16 18:04 UTC, tvivls commented on src/components/Navigation/Navigation.jsx
> +  const [refSB, showSB, setShowSB] = usePopup();
аналогично
непонятно что за SB
исправь везде

2024-07-16 18:04 UTC, tvivls commented on src/components/Navigation/Navigation.jsx
> +            setShowSB((v) => !v);
`v`)))
исправь везде этот нейминг

2024-07-16 18:04 UTC, tvivls commented on src/components/Sidebar/Sidebar.jsx
> +            </li>
тоже попробуй сократить

2024-07-16 18:04 UTC, tvivls commented on src/hooks/usePopup.js
> +  return [ref, show, setShow];
лучше возвращать объект, меньше шанс ошибиться. а так можешь перепутать местами элементы и использовать их неправильно

2024-07-16 18:08 UTC, tvivls commented on src/components/Loader/Loader.module.css
> +  height: 47px;
давай округлим

2024-07-16 18:08 UTC, tvivls commented on src/index.css
> +  max-width: 1280px;
почему не 100% ?
в целом, нашла два-три места, где пишешь max/min значения для width/height, нельзя их исправить на %, padding (не считая иконок каких-нибудь)?

2024-07-22 16:46 UTC, Warckut commented on src/components/Navigation/Navigation.jsx
> +            setShowSB((v) => !v);
Извини, я думал что везде исправил, но сейчас точно все убрал

2024-07-22 16:46 UTC, Warckut commented
@tvivls, исправил

2024-08-02 05:14 UTC, Warckut commented
@tvivls, исправил

2024-08-27 14:03 UTC, tvivls approved these changes

2024-08-27 14:03 UTC, tvivls commented on src/assets/img/antidepressants.png
если картинки весят много - их можно сжать
https://squoosh.app/ до 80% спокойно можно уменьшать

2024-08-27 14:03 UTC, tvivls commented on src/assets/svg/arrow-right.svg
для svg также можно использовать svgo (сайт или npm)
оптимизирует иконки, но может иногда портить их - тогда используем исходную svg

2024-08-27 14:03 UTC, tvivls commented on src/components/Header/Mobile/Mobile.module.css
> +@media screen and (max-width: 1024px) {
зачем тебе на медиа `screen and`

2024-08-27 14:03 UTC, tvivls commented on src/components/Navigation/Navigation.jsx
> +    <>
было бы хорошо использовать `nav`

2024-08-28 00:47 UTC, merged