feature/auth
Warckut/landing-2024 pull request #5
Opened 2024-06-27 14:04 UTC by osakac

2024-07-01 09:46 UTC, Warckut commented on src/pages/Auth/AuthLayout.jsx
> +import image from '../../assets/img/auth-img.png';
Это изображение узкое и взято из страницы, а в макете есть отдельное изображение большего размера. Если взять второе, то можно добавить для img свойство object-fit: cover и оно не будет растягиваться

2024-07-01 09:46 UTC, Warckut commented on src/assets/styles/variables.css
> +  --color-primary-60: #0f62fe;
Несмотря на то, что в макете на странице colors --color-primary-60 указан как #0f62fe, в макете вместо этого цвета на всех кнопках используется #458ff6, тут наверное нужно посоветоваться с куратором, но мне кажется лучше использовать второй

2024-07-01 10:04 UTC, osakac commented on src/assets/styles/variables.css
> +  --color-primary-60: #0f62fe;
✅

2024-07-01 19:02 UTC, tvivls requested changes

2024-07-01 19:02 UTC, tvivls commented on src/components/Button/Button.jsx
> +    <button className={`${btnSize[size]} ${btnType[type]}`} style={{ ...props, padding: `${py}px ${px}px` }}>
лучше по минимуму использовать inline стили

2024-07-01 19:02 UTC, tvivls commented on src/components/Button/Button.jsx
> +    <button className={`${btnSize[size]} ${btnType[type]}`} style={{ ...props, padding: `${py}px ${px}px` }}>
у Саши в ПР используется classnames, используй тоже эту библиотеку

2024-07-01 19:02 UTC, tvivls commented on src/components/Checkbox/Checkbox.jsx
> +import cl from './Checkbox.module.css';
непонятное название

2024-07-01 19:02 UTC, tvivls commented on src/components/FormInput/FormInput.module.css
> +.eyeBtn {
не используй теги в названиях классов
названия должны отражать суть класса

2024-07-01 19:02 UTC, tvivls commented on src/pages/Auth/Login/Login.module.css
> +  max-width: 560px;
я писала про размеры
Ширина в процентах - норм, но фиксированная ширина в пикселях - нет.

2024-07-01 21:37 UTC, osakac commented on src/components/Button/Button.jsx
> +    <button className={`${btnSize[size]} ${btnType[type]}`} style={{ ...props, padding: `${py}px ${px}px` }}>
props убрал, но как падинг вынести не придумал

2024-07-01 21:38 UTC, osakac commented on src/pages/Auth/Login/Login.module.css
> +  max-width: 560px;
она же не фиксированная, просто не будет растягиваться больше необходимого размера

2024-07-01 21:40 UTC, osakac commented on src/components/FormInput/FormInput.module.css
> +.eyeBtn {
разве в контексте инпута eyeBtn плохое название?

2024-07-05 21:53 UTC, tvivls commented on src/components/FormInput/FormInput.module.css
> +.eyeBtn {
я бы сказала, это название не совсем понятно. Более понятные названия - toggleVisibility, togglePasswordVisibility, passwordVisibility, showPassword, ... На мой взгляд, они более точно отражают предназначение класса.

2024-07-05 21:57 UTC, tvivls commented on src/pages/Auth/Login/Login.module.css
> +  max-width: 560px;
задай ей margin'ы/padding'и. это будет более правильно.

кстати словила вот такое 
<img width="1152" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/e001f89e-25ce-4941-865b-892c63dc13d0">

2024-07-09 13:19 UTC, osakac commented on src/pages/Auth/Login/Login.module.css
> +  max-width: 560px;
а что тут не так?

2024-07-16 17:42 UTC, tvivls commented on src/pages/Auth/Login/Login.module.css
> +  max-width: 560px;
картинка растянутя. можно сделать так, чтобы она нормально выглядела

2024-07-16 18:10 UTC, tvivls commented
конфликт

2025-02-21 14:13 UTC, closed without merging