feat(Block with form): реализация блока с формой
Warckut/landing-2024 pull request #6
Opened 2024-06-30 13:13 UTC by osakac

2024-07-01 20:06 UTC, tvivls requested changes
<img width="755" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/39e7b4dd-895e-4ceb-84a8-c6ffe13e15a7">
при выборе всех, не отмечаются все группы
+ текст после ввода выглядит как будто это placeholder, давай текст сделаем его черным цветом (а placeholder оставим таким).

картинку плющит
<img width="755" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/885a89b4-648d-4c43-b206-5c3156cc36c8">

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +const data = [
вынеси в константы

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +export default function FormInputSelect({ fieldName }) {
может ограничить его по высоте, а внутри сделать скролл ? если слишком много данных, селект будет очень большим

2024-07-01 20:06 UTC, tvivls commented on src/components/sections/cooperation/CooperationSection.module.css
> +.fio {
что за fio?
userName какой-нибудь
fullName

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +      const newGroups = data.filter((item) => item.id.startsWith(e.target.id));
переиспользуй e.target.id и e.target.checked

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +      const newGroups = data.filter((item) => item.id.startsWith(e.target.id));
дублируется

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +      setSelected((selected) => selected.filter((item1) => !newGroups.map((item2) => item2.id).includes(item1)));
item1, item2 - плохие названия

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +    const parent = data.find((item) => item.id === group.parentId);
а если group не будет ?

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +    if (!parent) return;
полностью дублирует 155-157 строки

2024-07-01 20:06 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +      if (selectRef.current?.contains(e.target)) return;
если пишешь return после if, `else` не обязательно ставить

2024-07-01 20:06 UTC, tvivls commented on src/components/sections/prices/PricesSection.jsx
> +            <span className={`${cl.discount} body-xs`}>20% дешевле</span>
сделай по центру

2024-07-01 20:07 UTC, tvivls commented
<img width="755" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/07c28951-8120-40f6-a356-477331f8112b">
специалисты съехали в право. сделай по центру

2024-07-01 20:08 UTC, tvivls commented
и при нажатии на кнопку "Начать", кидает на /login. так задумано ?

2024-07-01 21:53 UTC, osakac commented on src/components/sections/prices/PricesSection.jsx
> +            <span className={`${cl.discount} body-xs`}>20% дешевле</span>
не понял, он же уже по центру

2024-07-01 22:29 UTC, osakac commented on src/components/FormInput/FormInputSelect.jsx
> +      const newGroups = data.filter((item) => item.id.startsWith(e.target.id));
не понял

2024-07-01 22:31 UTC, osakac commented on src/components/FormInput/FormInputSelect.jsx
> +const data = [
не понял

2024-07-05 20:09 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +const data = [
в отдельный файл с константами. Обычно делают отдельные файлы с типами, отдельно с константами, а в самих компонентах их импортируют

2024-07-05 20:11 UTC, tvivls commented on src/components/FormInput/FormInputSelect.jsx
> +      const newGroups = data.filter((item) => item.id.startsWith(e.target.id));
вынеси их в разные константы. И эти константы уже используй. Чтобы каждый раз не писать обращение до id и checked

2024-07-05 20:13 UTC, tvivls commented on src/components/sections/prices/PricesSection.jsx
> +            <span className={`${cl.discount} body-xs`}>20% дешевле</span>
<img width="275" alt="image" src="https://github.com/Warckut/landing-2024/assets/86954004/04e0de8a-53d6-4f25-a487-76871350fdcd">
"20% дешевле" не по центру относительно страницы

2024-07-07 17:13 UTC, osakac commented on src/components/sections/prices/PricesSection.jsx
> +            <span className={`${cl.discount} body-xs`}>20% дешевле</span>
разве логика не в том чтобы эта плашка была конкретно над "год" (+ по макету)

2025-02-21 14:13 UTC, closed without merging